config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :cubes, only: [:index, :show, :edit, :new, :create]
  resources :cube_cards, only: [:show, :edit, :update, :destroy]
  resource :display_card do
    member do
      get :route
    end
  end
  resources :drafts, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      post :start
      post :pick_list_size
    end
    resources :transfer_portal_transactions, only: [:index, :create]
  end
  resources :draft_chat_messages, only: [:create]
  resources :draft_participants, only: [:new, :create, :edit, :update] do
    member do
      get :picks
      get :pick_queue
    end
    resources :transfer_portal_transactions, only: [:new]
  end
  resources :participant_picks, only: [:new, :create, :update] do
    member do
      get :hovercard
    end
  end
  resources :queued_picks, only: [:new, :create, :destroy] do
    collection do
      patch :update_order
    end
  end
  resources :surrogate_draft_participants, only: [:new, :create]
  resources :transfer_portal_transactions do
    member do
      post :accept
      post :reject
      post :cancel
    end
  end
  devise_for :users, :controllers => { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  get '/up', to: 'health#up'

  # Defines the root path route ("/")
  root to: "drafts#index"
end

app/models/draft_participant.rb
# == Schema Information
#
# Table name: draft_participants
#
#  id                 :uuid             not null, primary key
#  display_color      :string
#  display_name       :string           not null
#  draft_position     :integer
#  queue_active       :boolean          default(FALSE), not null
#  queue_minute_delay :integer          default(0), not null
#  skipped            :boolean          default(FALSE)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  draft_id           :uuid
#  surrogate_user_id  :uuid
#  user_id            :uuid
#
# Indexes
#
#  index_draft_participants_on_draft_id                     (draft_id)
#  index_draft_participants_on_draft_id_and_draft_position  (draft_id,draft_position) UNIQUE
#  index_draft_participants_on_draft_id_and_user_id         (draft_id,user_id) UNIQUE
#  index_draft_participants_on_draft_position_skipped       (draft_id,draft_position,skipped)
#  index_draft_participants_on_surrogate_user_id            (surrogate_user_id)
#  index_draft_participants_on_user_id                      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (draft_id => drafts.id)
#  fk_rails_...  (surrogate_user_id => users.id)
#  fk_rails_...  (user_id => users.id)
#
class DraftParticipant < ApplicationRecord
  belongs_to :draft, counter_cache: :participants_count
  belongs_to :user
  has_many :participant_picks
  has_many :queued_picks
  has_many :cube_cards, :through => :participant_picks
  has_many :surrogate_draft_participants
  has_many :surrogate_participants, through: :surrogate_draft_participants

  scope :unskipped, -> { where(skipped: false) }
  scope :skipped, -> { where(skipped: true) }
  scope :ordered, -> { order(:draft_position) }
  scope :reversed, -> { order(draft_position: :desc) } 
   
  DISPLAY_COLORS = %w[#e6194b #3cb44b #ffe338 #4363d8 #f58231 #911eb4 #46f0f0 #f032e6 #bcf60c #fabebe #008080 #e6beff #9a6324 #a58559 #800000 #76dbaa #808000 #ffd8b1 #000075 #808080]
  
  def set_display_color!
    color = (DISPLAY_COLORS - draft.draft_participants.map(&:display_color)).sample
    update!(display_color: color)
  end

  def pick_card!(cube_card)
    pick = next_pick
    pick.update!(cube_card: cube_card, skipped: false)
    if skipped?
      if draft.last_pick_number < next_pick_number
        update!(skipped: false)
      end
    else
      draft.update!(last_pick_at: pick.updated_at)
      if pick.pick_number == draft.participants_count * draft.rounds
        draft.completed!
      else
        draft.enqueue_skip_job
        draft.active_pick.enqueue_auto_pick_job
      end
    end
    
    RemoveQueuedPicksJob.perform_later(pick)
    Broadcast::DraftUpdateJob.perform_later(draft)
    pick
  end

  def can_pick_for?(draft_participant)
    draft_participant == self || draft_participant.surrogate_participants.include?(self)
  end

  def cardpool
    cube_cards.sort_by(&:custom_cmc).map do |cube_card|
      cube_card.card.name
    end
  end

  def calculate_pick_number(round)
    total_drafters = draft.participants_count
    if round % 2 == 1
      ((round-1) * total_drafters + draft_position)
    else
      round * total_drafters - draft_position + 1
    end
  end

  private

  def next_pick
    ParticipantPick.where(cube_card: nil, draft_participant: self).order(:pick_number).first
  end

  def next_pick_number
    calculate_pick_number(next_pick_round)
  end

  def next_pick_round
    next_pick&.round || draft.rounds + 1
  end
end

app/controllers/draft_participants_controller.rb
class DraftParticipantsController < ApplicationController
  def new
    @draft = Draft.find(params[:draft_id])
  end

  def create
    draft_participant = DraftParticipant.create(create_params)
    draft_participant.set_display_color!
    redirect_to draft_path(draft_participant.draft)
  end

  def edit
    @draft_participant = DraftParticipant.find(params[:id])
  end

  def update
    @draft_participant = DraftParticipant.find(params[:id])
    @draft_participant.update!(update_params)

    respond_to do |format|
      format.turbo_stream { flash.now[:success] = "Settings saved" }
      format.html do
        flash[:success] = "Settings saved"
        redirect_to draft_path(@draft_participant.draft)
      end
    end
  end

  def picks
    @draft_participant = DraftParticipant.find(params[:id])
  end

  def pick_queue
    @draft_participant = DraftParticipant.find(params[:id])

    redirect_to draft_path(@draft_participant.draft) if @draft_participant.user != current_user
  end

  private

  def create_params
    params.require(:draft_participant).permit(
      :draft_id,
      :user_id,
      :display_name
    )
  end

  def update_params
    params.require(:draft_participant).permit(
      :display_name,
      :queue_active,
      :queue_minute_delay
    )
  end
end

app/views/draft_participants/edit.html.erb
<div class="text-center mb-2">
  <%= button_to("Back", draft_path(@draft_participant.draft), method: :get, class: "btn btn-warning mt-2") %>
</div>
<%= render(DisplayCardComponent.new(width: :lg)) do %>
  <div class="card-header">DRAFTER SETTINGS</div>
  <%= form_with(model: @draft_participant, data: { turbo: false }) do |f| %>
    <div class="container col-sm-2">
      <%= f.label :card_text do %>
        <div class="fw-bold text-center">
          Name
        </div>
      <% end %>
      <%= f.text_field :display_name, value: @draft_participant.display_name, class: "d-block w-100 mb-1" %>
      <%= render(ButtonComponent.new(classes: "mb-1")) {"Update"} %>
    </div>
  <% end %>
  <div class="container">
    <%= render(ButtonComponent.new(url: new_surrogate_draft_participant_path(draft_participant_id: @draft_participant.id), variation: :primary, data: { turbo_frame: "modal" })) { "Add Surrogate" } %>
  </div>
<% end %>

app/views/draft_participants/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal d-block" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= form_with(model: DraftParticipant.new, data: { controller: "form-redirect", action: "turbo:submit-end->form-redirect#next" }) do |f| %>
          <div class="modal-header">
            <h5 class="modal-title">Join Draft</h5>
            <%= render(ButtonComponent.new(variation: :close, data: { controller: "modal", action: "modal#close"})) %>
          </div>
          <div class="modal-body">
            <div class="mb-3">
              Join <%= @draft.name %>?
              <%= f.hidden_field :draft_id, value: @draft.id %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :display_name, value: current_user.username %>
            </div>
          </div>
          <div class="modal-footer">
            <%= f.submit "Yes", class: "btn btn-primary btn-block" %>
            <%= render(ButtonComponent.new(url: "#", variation: :secondary, data: { controller: "modal", action: "modal#close"})) {"No"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/draft_participants/pick_queue.html.erb
<div class="text-center mb-2">
  <%= button_to("Back", draft_path(@draft_participant.draft), method: :get, class: "btn btn-warning mt-2") %>
</div>
<%= render(DraftParticipantQueuedPicksComponent.new(draft_participant: @draft_participant)) %>

app/views/draft_participants/picks.html.erb
<div class="d-flex justify-content-center">
  <%= button_to("Back", draft_path(@draft_participant.draft), method: :get, class: "btn btn-warning mx-2") %>
  <div data-controller="clipboard" data-clipboard-cardpool-value='<%= @draft_participant.cardpool.join("\n") %>'>
    <button class="btn btn-light mx-2" data-action="click->clipboard#copy" data-clipboard-target="button">Copy</button>
  </div>
</div>
<div class="pt-2">
  <%= render(DraftParticipantCardPoolComponent.new(draft_participant: @draft_participant)) %>
</div>

app/views/draft_participants/update.turbo_stream.erb
<turbo-stream action="replace" target="flash">
  <template>
    <div id="flash" class="sticky z-50 px-16 rounded-lg top-2" >
      <% flash.each do |key, message| %>
        <div class="alert <%= key == "error" ? "alert-danger" : "alert-success" %> fade show" data-controller="delayed-removal" data-delayed-removal-delay-value=<%= key == "error" ? "10000" : "4000" %>>
          <strong><%= key.upcase %>:</strong> <%= message %>
        </div>
      <% end %>
    </div>
  </template>
</turbo-stream>