config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :cubes, only: [:index, :show, :edit, :new, :create]
  resources :cube_cards, only: [:show, :edit, :update, :destroy]
  resource :display_card do
    member do
      get :route
    end
  end
  resources :drafts, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      post :start
      post :pick_list_size
    end
    resources :transfer_portal_transactions, only: [:index, :create]
  end
  resources :draft_chat_messages, only: [:create]
  resources :draft_participants, only: [:new, :create, :edit, :update] do
    member do
      get :picks
      get :pick_queue
    end
    resources :transfer_portal_transactions, only: [:new]
  end
  resources :participant_picks, only: [:new, :create, :update] do
    member do
      get :hovercard
    end
  end
  resources :queued_picks, only: [:new, :create, :destroy] do
    collection do
      patch :update_order
    end
  end
  resources :surrogate_draft_participants, only: [:new, :create]
  resources :transfer_portal_transactions do
    member do
      post :accept
      post :reject
      post :cancel
    end
  end
  devise_for :users, :controllers => { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  get '/up', to: 'health#up'

  # Defines the root path route ("/")
  root to: "drafts#index"
end

app/models/cube_card.rb
# == Schema Information
#
# Table name: cube_cards
#
#  id                    :uuid             not null, primary key
#  count                 :integer          not null
#  custom_cmc            :integer          not null
#  custom_color_identity :string           not null, is an Array
#  custom_image          :string           not null
#  custom_set            :string           not null
#  soft_delete           :boolean          default(FALSE)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  card_id               :uuid
#  cube_id               :uuid
#
# Indexes
#
#  index_cube_cards_on_card_id                (card_id)
#  index_cube_cards_on_cube_id                (cube_id)
#  index_cube_cards_on_cube_soft_delete_cmc   (cube_id,soft_delete,custom_cmc)
#  index_cube_cards_on_custom_color_identity  (custom_color_identity)
#  index_cube_cards_on_soft_delete            (soft_delete)
#
# Foreign Keys
#
#  fk_rails_...  (card_id => cards.id)
#  fk_rails_...  (cube_id => cubes.id)
#
class CubeCard < ApplicationRecord
  class CreationError < StandardError;end
  include PgSearch::Model
  belongs_to :cube
  belongs_to :card

  validates :count, presence: true

  pg_search_scope :search_by_card_text, associated_against: {
    card: [:card_text]
  }, ignoring: :accents

  pg_search_scope :search_by_card_type, associated_against: {
    card: [:type_line]
  }, ignoring: :accents

  scope :active, -> { where(soft_delete: false) }
  scope :sorted, -> { joins('LEFT OUTER JOIN cards ON cube_cards.card_id = cards.id').order(:custom_cmc, Arel.sql("cards.type_line LIKE '\%Creature\%' DESC"), "cards.name") }
  scope :with_cmc, ->(cmc) { where(custom_cmc: cmc) if cmc.present? }
  scope :with_color, ->(color) { where("? = ANY (custom_color_identity)", color) if color.present? }
  scope :with_card_text_matching, ->(card_text) { search_by_card_text(card_text) if card_text.present? }
  scope :with_card_type_matching, ->(card_type) { search_by_card_type(card_type) if card_type.present? }
  scope :with_cmc_greater_than, -> (cmc) { where("custom_cmc > ?", cmc) }

  delegate :colorless?, :white?, :blue?, :black?, :red?, :green?, to: :color_identity

  def color_identity
    Card::ColorIdentity.new(custom_color_identity)
  end

  def image_url
    custom_image
  end
end

app/controllers/cube_cards_controller.rb
class CubeCardsController < ApplicationController
  def show
    @cube_card = CubeCard.find params[:id]
  end

  def edit
    @cube_card = CubeCard.find params[:id]
  end

  def update
    @cube_card = CubeCard.find params[:id]
    @cube_card.attributes = update_params.merge(custom_color_identity)
    if @cube_card.save
      flash[:success] = "Cube card changes saved"
      redirect_to cube_path(@cube_card.cube)
    else
      flash[:error] = "Cube card changes failed: #{@cube_card.errors.full_messages.join(" ")}"
      redirect_to edit_cube_card_path(@cube_card)
    end
  end

  def destroy
    @cube_card = CubeCard.find params[:id]
    @cube_card.update!(soft_delete: true)
    flash[:success] = "Cube card deleted"
    redirect_to cube_path(@cube_card.cube)
  end

  private

  def update_params
    params.require(:cube_card).permit(
      :count,
      :custom_set,
      :custom_image,
      :custom_cmc,
      custom_color_identity: []
    )
  end

  def custom_color_identity
    {
      custom_color_identity: update_params[:custom_color_identity].reject(&:blank?)
    }
  end
end

app/views/cube_cards/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal d-block" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= render(ButtonComponent.new(classes: "ms-auto", variation: :close, data: { controller: "modal", action: "modal#close"})) %>
        <div class="text-center"><%= @cube_card.card.name %></div>
        <%= form_with(model: @cube_card, local: true) do |f| %>
          <div class="pt-3 row justify-content-center">
            <div class="col-6 text-start d-grid gap-2">
              <div>
                <%= f.label :custom_color_identity, "Color Identity", class: "fw-bold" %>
                <%= f.select :custom_color_identity, Card::ColorIdentity::COLOR_IDENTITIES.invert, {}, { multiple: true, class: "form-control" } %>
              </div>
            </div>
          </div>

          <div class="row justify-content-center">
            <%= render(ButtonComponent.new(variation: :primary, classes: "col-2 mt-2", data: { turbo: false })) { "Update" } %>
          </div>
        <% end %>
        <%= form_with(url: cube_card_path(@cube_card), method: :delete) do |f| %>
          <div class="row justify-content-center">
            <%= render(ButtonComponent.new(variation: :danger, classes: "col-2 mt-2 mb-2", data: { turbo: false })) { "Delete" } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/cube_cards/show.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal d-block" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= render(ButtonComponent.new(classes: "ms-auto", variation: :close, data: { controller: "modal", action: "modal#close"})) %>
        <div class="text-center"><%= @cube_card.card.name %></div>
        <div class="pt-3 row justify-content-center mb-4">
          <%= image_tag(@cube_card.image_url, class: "cube_card__img__static") %>
          <%= render(ScryfallLinkComponent.new(card: @cube_card.card)) %>
        </div>
      </div>
    </div>
  </div>
<% end %>