config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :cubes, only: [:index, :show, :edit, :new, :create]
  resources :cube_cards, only: [:show, :edit, :update, :destroy]
  resource :display_card do
    member do
      get :route
    end
  end
  resources :drafts, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      post :start
      post :pick_list_size
    end
    resources :transfer_portal_transactions, only: [:index, :create]
  end
  resources :draft_chat_messages, only: [:create]
  resources :draft_participants, only: [:new, :create, :edit, :update] do
    member do
      get :picks
      get :pick_queue
    end
    resources :transfer_portal_transactions, only: [:new]
  end
  resources :participant_picks, only: [:new, :create, :update] do
    member do
      get :hovercard
    end
  end
  resources :queued_picks, only: [:new, :create, :destroy] do
    collection do
      patch :update_order
    end
  end
  resources :surrogate_draft_participants, only: [:new, :create]
  resources :transfer_portal_transactions do
    member do
      post :accept
      post :reject
      post :cancel
    end
  end
  devise_for :users, :controllers => { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  get '/up', to: 'health#up'

  # Defines the root path route ("/")
  root to: "drafts#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row">
      <% if user_signed_in? %>
        <div class="nav-item">
            <%= render(ButtonComponent.new(url: drafts_path, classes: "nav-link", data: { turbo_method: :get })) { "Drafts" } %>
        </div>
        <div class="nav-item">
            <%= render(ButtonComponent.new(url: cubes_path, classes: "nav-link", data: { turbo_method: :get })) { "Cubes" } %>
        </div>
        <div class="nav-item ms-auto">
            <%= render(ButtonComponent.new(url: destroy_user_session_path, classes: "nav-link", data: { turbo_method: :delete })) { "Log out" } %>
        </div>
      <% else %>
        <div class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </div>
        <div class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </div>
      <% end %> 
    </div>
  </div>
</nav>