config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :cubes, only: [:index, :show, :edit, :new, :create]
  resources :cube_cards, only: [:show, :edit, :update, :destroy]
  resource :display_card do
    member do
      get :route
    end
  end
  resources :drafts, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      post :start
      post :pick_list_size
    end
    resources :transfer_portal_transactions, only: [:index, :create]
  end
  resources :draft_chat_messages, only: [:create]
  resources :draft_participants, only: [:new, :create, :edit, :update] do
    member do
      get :picks
      get :pick_queue
    end
    resources :transfer_portal_transactions, only: [:new]
  end
  resources :participant_picks, only: [:new, :create, :update] do
    member do
      get :hovercard
    end
  end
  resources :queued_picks, only: [:new, :create, :destroy] do
    collection do
      patch :update_order
    end
  end
  resources :surrogate_draft_participants, only: [:new, :create]
  resources :transfer_portal_transactions do
    member do
      post :accept
      post :reject
      post :cancel
    end
  end
  devise_for :users, :controllers => { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  get '/up', to: 'health#up'

  # Defines the root path route ("/")
  root to: "drafts#index"
end

app/models/draft.rb
# == Schema Information
#
# Table name: drafts
#
#  id                 :uuid             not null, primary key
#  last_pick_at       :datetime
#  name               :string           not null
#  participants_count :integer          default(0), not null
#  rounds             :integer          not null
#  status             :string           not null
#  timer_minutes      :integer
#  transfers_allowed  :boolean
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  cube_id            :uuid
#  user_id            :uuid
#
# Indexes
#
#  index_drafts_on_cube_id  (cube_id)
#  index_drafts_on_name     (name)
#  index_drafts_on_status   (status)
#  index_drafts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (cube_id => cubes.id)
#  fk_rails_...  (user_id => users.id)
#
class Draft < ApplicationRecord
  belongs_to :cube
  belongs_to :owner, foreign_key: :user_id, class_name: "User"
  has_many :draft_participants, counter_cache: :participants_count
  has_many :users, :through => :draft_participants
  has_many :participant_picks, :through => :draft_participants
  has_many :draft_chat_messages
  has_many :transfer_portal_transactions
  has_many :transfer_portal_transaction_offerings, :through => :transfer_portal_transactions
  enum :status, DraftStatus.all.zip(DraftStatus.all).to_h

  scope :pending, -> { where(status: DraftStatus.pending) }
  scope :with_full_associations, -> {
    includes(
      :cube,
      draft_participants: :user,
      participant_picks: [
        :draft_participant,
        { cube_card: :card }
      ]
    )
  }

  def set_participant_positions!
    draft_participants.shuffle.each.with_index do |participant, i|
      participant.update(draft_position: i + 1)
    end
  end

  def setup_picks!
    draft_participants.order(:draft_position).each do |draft_participant|
      rounds.times.with_index do |i|
        draft_participant.participant_picks.create!(round: i + 1, pick_number: draft_participant.calculate_pick_number(i + 1))
      end
    end
  end

  def active_pick
    participant_picks.find_by(pick_number: last_pick_number + 1)
  end

  def active_participant
    active_pick&.draft_participant
  end

  def last_pick_number
    participant_picks.where.not(cube_card_id: nil)
      .or(
        participant_picks.where(skipped: true)
      ).maximum(:pick_number) || 0
  end

  def timer_live?
    active? && timer_minutes.present? && after_initial_rounds?
  end

  def enqueue_skip_job
    if timer_live?
      SkipActiveParticipantJob.set(wait: seconds_until_skip).perform_later(active_pick)
    end
  end

  private

  def seconds_until_skip
    return 0 if active_participant.skipped?

    TimerCalculator.new(last_pick_at, timer_minutes).calculate_target_end.to_i - Time.now.to_i
  end

  def after_initial_rounds?
    return false unless active_pick.present?
    active_pick.round > 2
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :find_draft, only: [:show, :edit, :update, :start, :pick_list_size]
  before_action :set_context, only: [:show, :pick_list_size]
  before_action :set_display_defaults, only: [:show]
  def index
  end

  def show
    @cube_cards = @draft.cube.cube_cards
      .includes(:card)
      .select(
        "cube_cards.*",
        "cards.name",
        "cards.type_line",
        "cards.card_text"
      )
      .active.sorted
      .with_cmc(filter_params[:cmc])
      .with_color(filter_params[:color])
      .with_card_text_matching(filter_params[:card_text])
      .with_card_type_matching(filter_params[:card_type])
  end

  def edit
    if @draft.status != DraftStatus.pending
      redirect_to draft_path(@draft)
    end
  end

  def update
    @draft.update(update_params)
    redirect_to draft_path(@draft)
  end

  def start
    if @draft.status == "pending"
      @draft.set_participant_positions!
      @draft.setup_picks!
      @draft.update!(status: "active")
      redirect_to draft_path(@draft)
    else
      flash[:error] = "Can only start a pending draft."
      redirect_to draft_path(@draft)
    end
  end

  def new
  end

  def create
    ActiveRecord::Base.transaction do
      @draft = Draft.create(
        name: create_params[:name],
        rounds: create_params[:rounds],
        timer_minutes: create_params[:timer_minutes],
        cube: Cube.find(create_params[:cube_id]),
        owner: current_user,
        status: DraftStatus.pending,
        transfers_allowed: create_params[:transfers_allowed]
      )
      @draft.draft_participants.create(user: current_user, display_name: current_user.username)
      redirect_to drafts_path
    end
  end

  def pick_list_size
    current_user.update!(pick_list_size: params[:text_size], secret_key: ENV.fetch("REGISTRATION_SECRET"))
    
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "draft_#{@draft.id}_pick_list",
          render_to_string(PickListComponent.new(draft: @draft, context: @context))
        )
      end
      format.html { redirect_to draft_path(@draft) }
    end
  end

  private

  helper_method def filter_params
    return {} unless params[:filters].present?

    params.require(:filters).permit(:cmc, :color, :card_text, :card_type, :text_only, :image_size)
  end

  def create_params
    params.require(:draft).permit(
      :name,
      :rounds,
      :cube_id,
      :timer_minutes,
      :transfers_allowed
    )
  end

  def update_params
    params.require(:draft).permit(
      :status
    )
  end

  def find_draft
    @draft = Draft.with_full_associations.find(params[:id])
  end

  def set_display_defaults
    if filter_params[:text_only].present? || filter_params[:image_size].present?
      current_user.default_display = filter_params[:text_only] == "1" ? "text" : "image"
      current_user.default_image_size = filter_params[:image_size] || current_user.default_image_size
      current_user.save!(validate: false)
    end
  end

  def set_context
    @draft_participant = @draft.draft_participants.find { |p| p.user_id == current_user.id }

    @context = MagicCardContext.for_active_draft(
      draft: @draft, 
      draft_participant: @draft_participant,
      text_only: current_user.default_display == "text", 
      image_size: current_user.default_image_size)
  end
end

app/views/drafts/_pending.html.erb
<%= render(DisplayCardComponent.new(width: :sm, classes: "mb-2")) do %>
  <p class="h1"><%= @draft.name %></p>
<% end %>
<% if @draft.owner == current_user %>
  <div class="container text-center mb-2">
    <%= form_with(url: start_draft_path(@draft)) do |f| %>
      <%= render(ButtonComponent.new) {"Start Draft"} %>
    <% end %>
  </div>
<% end %>
<% unless @draft.users.include? current_user %>
  <div class="container text-center mb-2">
    <%= render(ButtonComponent.new(url: new_draft_participant_path(draft_id: @draft.id), variation: :primary, data: { turbo_frame: "modal" })) { "Join" } %>
  </div>
<% end %>
<%= render(DraftDetailsComponent.new(draft: @draft)) %>
<%= render(ParticipantsListComponent.new(draft: @draft)) %>

app/views/drafts/_pick.html.erb
<%= render(PickComponent.new(pick)) %>

app/views/drafts/_show_body.html.erb
<div id="draft_<%= draft.id %>_show_body">
  <%= render(TimerComponent.new(draft: draft)) %>
  <div class="d-flex flex-md-row flex-column w-100">
    <%= render(PickListComponent.new(draft: draft, context: context)) %>
  </div>
  <%= render(CubeFiltersComponent.new(url: draft_path(draft), filter_params: filter_params, user: context.draft_participant&.user)) %>
  <%= render(CubeCardListComponent.new(cube_cards: cube_cards, context: context)) %>
</div>

app/views/drafts/create.html.erb
<h1>Drafts#create</h1>
<p>Find me in app/views/drafts/create.html.erb</p>

app/views/drafts/edit.html.erb
<h1><%= @draft.name %></h1>
<%= render(ParticipantsListComponent.new(draft: @draft)) %>
<div class="text-center">
  <%= render(ButtonComponent.new(url: edit_draft_path(@draft), variation: :primary)) {"Edit Draft"} %>
</div>

app/views/drafts/index.html.erb
<%= render(DisplayCardComponent.new(width: :lg)) do %>
  <div class="card-header">DRAFTS</div>
  <%= render(DraftListComponent.new(user: current_user)) %>
  <div class="text-center">
    <%= render(ButtonComponent.new(url: new_draft_path, variation: :primary, classes: "mb-2 mt-2")) { "New Draft" } %>
  </div>
<% end %>

app/views/drafts/new.html.erb
<%= render(DisplayCardComponent.new(width: :md)) do %>
  <div class="card-header">NEW DRAFT</div>
  <%= form_with(model: Draft.new, local: true) do |f| %>
    <div class="pt-3 row justify-content-center">
      <div class="col-6 text-start d-grid gap-2">
        <div class="col-12">
          <%= f.label :name, "Draft Name", class: "fw-bold" %>
          <%= f.text_field :name, class: "d-block" %>
        </div>
        <div class="col-12">
          <%= f.label :rounds, "Number of Rounds", class: "fw-bold" %>
          <%= f.text_field :rounds, class: "d-block" %>
        </div>
        <div class="col-12">
          <%= f.label :timer_minutes, "Pick Timer in Minutes", class: "fw-bold" %>
          <%= f.number_field :timer_minutes, class: "d-block" %>
        </div>
        <div class="col-12">
          <%= f.check_box :transfers_allowed, checked_value: true, unchecked_value:false %>
          <%= f.label :transfers_allowed do %>
            <div class="fw-bold text-center">
              Allow Trades
            </div>
          <% end %>
        </div>
        <div class="col-12">
          <%= f.label :cube_id, "Cube", class: "fw-bold" %>
          <%= f.collection_select :cube_id, Cube.where(owner: current_user).order(:name), :id, :name, {}, {class: "d-block"} %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <%= render(ButtonComponent.new(variation: :primary, classes: "mb-2 mt-2")) { "Create" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/drafts/show.html.erb
<%= turbo_stream_from @draft %>
<% if @draft.status == DraftStatus.pending %>
  <%= render "pending" %>
<% else %>
  <%= turbo_stream_from current_user %>
  <%= render(DisplayCardComponent.new(width: :sm, classes: "mb-2")) do %>
    <p class="h1"><%= @draft.name %></p>
  <% end %>
  <% if @context.draft_participant.present? %>
    <div class="d-flex mb-2 justify-content-center gap-2">
      <%= render(ButtonComponent.new(url: edit_draft_participant_path(@context.draft_participant), variation: :primary)) { "Drafter Settings" } %>
      <%= render(ButtonComponent.new(url: pick_queue_draft_participant_path(@context.draft_participant), variation: :primary)) { "Pick Queue" } %>
      <% if @draft.transfers_allowed %>
        <%= render(ButtonComponent.new(url: draft_transfer_portal_transactions_path(@draft), variation: :primary)) { "Transfer Portal" } %>
      <% end %>
    </div>
  <% end %>
  <div id="draft_<%= @draft.id %>_show_body">
    <%= render 'drafts/show_body', draft: @draft, context: @context, filter_params: filter_params, cube_cards: @cube_cards %>
  </div>
<% end %>